name: Sync MD to issues

on:
  push:
    branches: [ sync-md ]
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install
        shell: "bash"
        run: pnpm --filter sync-md install
      - name: Build
        shell: "bash"
        run: pnpm --filter sync-md bundle
  sync:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: run local action
        uses: ./packages/sync-md
        with:
          path: ./data/poem.md
        env: # Or as an environment variable
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

